# custom
[buildPlans.iosevka-custom]
family = "Iosevka Term"
design = ["term", "v-asterisk-low"]

[buildPlans.iosevka-custom.weights.regular]
shape = 400
css   = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
css   = 700

[buildPlans.iosevka-custom.slants]
upright = "normal"
italic = "italic"