[buildPlans.iosevka-custom]      # <iosevka-custom> is your plan name
family = "Iosevka Term"          # Font menu family name

spacing = "fontconfig-mono"      # Optional; Values: `normal`, `term`,
                                 # `fontconfig-mono`, or `fixed`
no-ligation = true

# serifs = "sans"                  # Optional; Values: `sans` or `slab`

# Optional; Configure single character's variant
[buildPlans.iosevka-custom.variants.design]
asterisk = "penta-low"

[buildPlans.iosevka-custom.variants.upright]
# g = "double-storey"
percent = "dots"
# tilde = "low"
# capital-q = 'straight'
# a = 'single-storey'
# three = 'flattop'
# dollar = 'open'

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-custom.slopes]
upright = "normal"
italic = "italic"

[buildPlans.iosevka-custom.widths.normal]
shape = 500        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.
